config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :nodes_users
  resources :categories
  resources :nodes do
    resources :events
    resources :participants
  end

  resources :events do
    resources :members
  end

  root 'nodes#index'

end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :users
  has_many :events
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @node, status: :ok }
    end
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name)
    end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<style>
  .enter{
    position: fixed;
    background-color: rgba(0,0,0,0.8);
    width:100%;
    height:100%;
    top:0;
    left:0;
    right:0;
    bottom:0;
  }
  .enter>h1{
    width:960px;
    margin: 250px auto;
    color:#fff;
    text-align: center;
    font-size: 140px;
    letter-spacing: 5px;
  }

  .enter>h1 .w{
    position:relative;
    -webkit-animation: w 1s;
  }
  @-webkit-keyframes w {
    from {top: 300px;opacity:0;}
    to {top: 0px;opacity:1;}
  }
  .enter>h1 .a{
    position:relative;
    -webkit-animation: a 1s;
  }
  @-webkit-keyframes a {
    from {bottom: 300px;opacity:0;}
    to {bottom: 0px;opacity:1;}
  }
  .enter>h1 .beacon{
    position:relative;
    -webkit-animation: beacon 2s ease-out;
  }
  @-webkit-keyframes beacon {
    0%{left: 300px;opacity:0;}
    50% {left: 300px;opacity:0;}
    100% {left: 0px;opacity:1;}
  }

</style>
<h1>Listing Nodes</h1>
<!-- <div class="enter">
  <h1><span class="w">W</span><span class="a">a</span><span class="beacon">Beacon</span></h1>
</div> -->
<table class="table">
  <thead>
    <tr>
      <th>Node ID</th>
      <th>Name</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.id %></td>
        <td><%= node.name %></td>
        <td><%= link_to 'Show Events', node_events_path(node) %> (<%= node.events.count %>)</td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>id:</strong>
  <%= @node.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>