config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :nodes_users
  resources :categories
  resources :nodes do
    resources :events
    resources :participants
  end

  resources :events do
    resources :members
  end

  root 'nodes#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :category
  belongs_to :node
  has_many :event_user_associations, :dependent => :destroy
  has_many :users, :through => :event_user_associations
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Node.find(params[:node_id]).events.all
    respond_to do |format|
      format.html
      format.json {render json: @events, status: :ok }
    end
  end

  def show
    @node = Node.find(params[:node_id])
    @event = @node.events.find(params[:id])
  end

  def new
    @node = Node.find(params[:node_id])
    @event = @node.events.build()
  end

  def edit
    @node = Node.find(params[:node_id])
    @event = @node.events.find(params[:id])
  end

  def create
    @node = Node.find(params[:node_id])
    @event = @node.events.build(event_params)
    @member = @event.event_user_associations.build(user_id: event_params[:creator_id])
    respond_to do |format|
      if @event.save && @member.save
        format.html {render :show}
        format.json {render json: @node.events, status: :ok }
      else
        format.html
        format.json {render json: @events.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @node = Node.find(params[:node_id])
    @event = @node.events.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        format.html {redirect_to [@node, @event], notice: 'Event was successfully updated.'}
        format.json {render json: @node.events, status: :ok }
      else
        format.html {render :edit}
        format.json {render json: @events.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @node = Node.find(params[:node_id])
    @event = @node.events.find(params[:id]).delete()
    respond_to do |format|
      format.html {redirect_to node_events_path(@node), notice: 'Event was successfully destroyed.'}
      format.json {render json: @node.events, status: :ok }
    end
  end


  private
    def event_params
      params.require(:event).permit(:creator_id, :category_id, :title, :content, :number, :end_time)
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for([@node ,@event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :creator_id %><br>
    <%= f.number_field :creator_id %>
  </div>
<!--   <div class="field">
    <%#= f.label :node_id %><br>
    <%#= f.number_field :node_id %>
  </div> -->
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_field :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', node_event_path(@event.node, @event) %> |
<%= link_to 'Back', node_events_path %>

app/views/events/index.html.erb
<h1>Listing Events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Event ID</th>
      <th>Title</th>
      <th>Content</th>
      <th>Number</th>
      <th>Creator</th>
      <th>Node</th>
      <th>Category</th>
      <th>End Time</th>
      <th>目前人數</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.title %></td>
        <td><%= event.content %></td>
        <td><%= event.number %></td>
        <td><%= event.creator_id %></td>
        <td><%= event.node_id %></td>
        <td><%= event.category_id %></td>
        <td><%= event.end_time %></td>
        <td><%= event.event_user_associations_count %></td>
        <td><%= link_to 'Members', event_members_path(event) %></td>
        <td><%= link_to 'Show', node_event_path(event.node, event) %></td>
        <td><%= link_to 'Edit', edit_node_event_path(event.node, event) %></td>
        <td><%= link_to 'Destroy', node_event_path(event.node, event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_node_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', node_events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @event.content %>
</p>

<p>
  <strong>Number:</strong>
  <%= @event.number %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @event.creator_id %>
</p>

<p>
  <strong>Node:</strong>
  <%= @event.node_id %>
</p>
<p>
  <strong>End Time:</strong>
  <%= @event.end_time %>
</p>
<%= link_to 'Edit', edit_node_event_path(@node, @event) %> |
<%= link_to 'Back', node_events_path %>